### ISSUE TITLE
DBUtils self._con.ping

### ISSUE THREAD

**Issue by KissMeInTheDark** [Cito/DBUtils#18]
My project uses
    thrift : 0.9.3
    mysql-python : 1.2.5
    DBUtils : 1.2

DBPools = PooledDB(creator=MySQLdb, mincached=0, maxcached=100, maxusage=5, ...)

The database has returned content, however  The server never returned. When I forcibly shut down the service,throw...

Traceback (most recent call last):
  File "SJSrcApp.py", line 1934, in <module>
    tmpServer.serve()
  File "/home/wxmemberapp/env/local/lib/python2.7/site-packages/thrift/server/TS                                                                                                                                                             erver.py", line 252, in serve
    self.processor.process(iprot, oprot)
  File "/home/wxmemberapp/env/local/lib/python2.7/site-packages/thrift/TMultiple                                                                                                                                                             xedProcessor.py", line 49, in process
    return self.services[serviceName].process(StoredMessageProtocol(iprot, stand                                                                                                                                                             ardMessage), oprot)
  File "/home/wxmemberapp/xhx/XHXWeight/XHXWeightSummary.py", line 2072, in proc                                                                                                                                                             ess
    self._processMap[name](self, seqid, iprot, oprot)
  File "/home/wxmemberapp/xhx/XHXWeight/XHXWeightSummary.py", line 2333, in proc                                                                                                                                                             ess_genPayOrder
    result.success = self._handler.genPayOrder(args.aCardNo, args.aPayType, args                                                                                                                                                             .aMoney)
  File "SJSrcApp.py", line 945, in genPayOrder
    tmpDatas = DBUtilsEx.executeProc('p_xhx_mobilepay_genPayOrder', (aCardNo, or                                                                                                                                                             der_id, aPayType, aMoney))
  File "/home/wxmemberapp/xhx/DBUtilsEx.py", line 69, in executeProc
    tmpDbConn = DBPools.connection()
  File "/home/wxmemberapp/env/local/lib/python2.7/site-packages/DBUtils/PooledDB                                                                                                                                                             .py", line 336, in connection
    con._ping_check()  # check connection
  File "/home/wxmemberapp/env/local/lib/python2.7/site-packages/DBUtils/SteadyDB                                                                                                                                                             .py", line 337, in _ping_check
    alive = self._con.ping()
KeyboardInterrupt

Where is the problem? is dbutils ? how to fix ? 
Thank you very much!

**Comment by Cito** [comment]
Without complete reproducible test case, it's hard to tell. Maybe ping() is not working properly in mysql-python. But I don't know, I always use DBUtils with Postgres. You can try whether setting ping=0 when creating PooledDB helps.
